---
- name: Update package cache
  apt:
      update_cache=yes
- name: Add openjdk-7 ppa 
  apt_repository:
      repo: 'ppa:openjdk-r/ppa'
      state: present
- name: Install GPG key from nodesource
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
- name: Add nodesource apt pkg index
  apt_repository:
      repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main' 
      state: present
      filename: "nodejs"
- name: Update package cache
  apt:
      update_cache=yes
- name: Install nodejs
  apt:
      name: nodejs
      state: present
- name: Install other pre-requesite packages
  apt: name={{item}} state=present
  with_items:
      - openssh-server
      - python-psycopg2
      - zip
      - unzip
      - openjdk-7-jdk
