---
- hosts: all
  become: yes
  roles:
    - { role: common, tags: "common" }
    - { role: vnc4, tags: "vnc4" }
    - { role: git, tags: "git" }
    - { role: docker, tags: "docker" }
    - { role: kubernetes, tags: "kubernetes" }
    - { role: minikube, tags: "minikube" }
