---
 - name: Install vnc
   apt: name={{item}} state=present
   with_items:
      - xorg
      - lxde
      - vnc4server

 - name: create vnc service startup script
   template:
     src=vncserver
     dest=/etc/init.d/vncserver
     mode=0755
 
 - name: create vnc user directory and password file
   copy:
     src=.vnc
     dest=/home/{{ user }}
     directory_mode=0700
     mode=0700
     owner={{ user }}
     group={{ user }}
     backup=yes
 
 - name: manage lxde configuration environment
   file:
     path=/home/{{ user }}/.config/pcmanfm/LXDE
     state=directory
     owner={{ user }}
     group={{ user }}
 
 - name: configure a nice background for lxde
   copy:
     src=lxde/openstackwallpaper1.png
     dest=/usr/share/lxde/wallpapers/openstackwallpaper1.png
 
 - name: configure pcmanfm
   template:
     src=desktop-items-0.conf
     dest=/home/{{ user }}/.config/pcmanfm/LXDE/desktop-items-0.conf
 
 - name: manage common desktop icons
   copy:
     src=lxde/Desktop
     dest=/home/{{ user }}
     owner={{ user }}
     group={{ user }}
 
 - name: Add vncserver service to default runlevels
   command: "update-rc.d vncserver defaults"
   tags: 
       - register-start-vnc

 - name: start vnc service
   service:
     name=vncserver
     state=restarted
     enabled=true
   tags:
       - register-start-vnc

