---
- name: Install git package
  apt:
      name: git
      state: present
- name: copy gitconfig
  template:
      src: gitconfig.j2
      dest: "/home/{{ ansible_ssh_user }}/.gitconfig"
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
